src/laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify'=>true]);

Route::get('/', function () {
	return view('welcome');
});
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth','verified'])
->prefix('RPD')
->group(function(){

	Route::get('/','RPDController@index')->name('RPD.index');
	Route::get('/filtrar','RPDController@filtrar')->name('RPD.filtrar');
	Route::get('/registro','RPDController@create')->name('RPD.registro');
	Route::get('/editar/{RPD}','RPDController@edit')->name('RPD.editar')->middleware('can:update,App\User');
	Route::get('/mostrar/{RPD}','RPDController@show')->name('RPD.ver');
	Route::get('/seguimiento/{RPD}','RPDController@seguimiento')->middleware('can:seguimiento,App\User')->name('RPD.seguimiento');
	Route::get('/canalizar/{RPD}','RPDController@canalizar')->middleware('can:seguimiento,App\User')->name('RPD.canalizar');

	Route::get('/carpeta/{RPD}','RPDController@carpeta')
	->middleware('can:seguimiento,App\User')->name('RPD.carpeta');

	Route::post('/carpeta/delete/','RPDController@deleteCarpeta')
	->middleware('can:seguimiento,App\User')->name('RPD.borrarFileCarpeta');
	

	Route::put('/trash/{RPD}','RPDController@destroy')->name('RPD.trash');	
	Route::put('/editar/{RPD}','RPDController@update')->name('RPD.editar');
	
	Route::post('/registro','RPDController@store')->name('RPD.registro');
	Route::post('/seguimiento/store/{RPD}','RPDController@storeSeguimiento')->name('RPD.storeSeguimiento');
	Route::post('/canalizar/store/{RPD}','RPDController@storeCanalizacion')->name('RPD.storeCanalizacion');
	Route::post('/carpeta/store/{RPD}','RPDController@storeCarpeta')->name('RPD.storeCarpeta');
	Route::post('/condicionLocalizacion/store/{RPD}','RPDController@storeCondicionLocalizacion')
			->name('RPD.storeCondicionLocalizacion');


	Route::get('/getPDF/{RPD}', 'RPDController@getPDF')->name('pdf.reporteRPD');
	Route::get('/ftVolante/{id}', 'RPDController@ftVolante')->name('pdf.volante');


	Route::get('/exportExcel/',function(){
		return (new App\Exports\RPDExport(request()->cookie('filtros')))
		->download('RPD.xlsx',\Maatwebsite\Excel\Excel::XLSX);
	})
	
	->name('RPD.exportExcel');
});

Route::middleware(['auth','verified','can:viewAny,App\User'])->prefix('admin')
->group(function(){
	
	Route::resource('usuario', 'UserController')
	->names([
		'create'   =>'usuario.crear'
		,'index'   =>'usuario.index'
		,'edit'    =>'usuario.editar'
		,'update'  =>'usuario.update'
	]);

	Route::put('usuario/trash/{usuario}','UserController@destroy')->name('usuario.trash');

	Route::put('usuario/restore/{id}','UserController@restore')
	->where('id', '[0-9]+')
	->name('usuario.restore');

	Route::resource('catalogo', 'CatalogoController')
	->names([
		'create'   =>'catalogo.crear'
		,'store'   =>'catalogo.store'
		,'index'   =>'catalogo.index'
		,'edit'    =>'catalogo.editar'
	]);

	Route::put('catalogo','CatalogoController@updateCatalogo')->name('catalogo.updateCatalogo');


	Route::get('index','adminController@index')->name('admin.index');

});


Route::post('ajax/folioCBP','AjaxController@getFolioCBP')->name('ajax.folioCBP');
Route::post('ajax/municipios','AjaxController@municipios')->name('ajax.municipios');
Route::post('ajax/localidades','AjaxController@localidades')->name('ajax.localidades');
Route::post('ajax/calcularEdad','AjaxController@calcularEdad')->name('ajax.calcularEdad');
Route::post('ajax/catalogo','AjaxController@catalogos')->name('ajax.catalogo');
Route::put('ajax/catalogo/trash','AjaxController@trashedCatalogo')->name('ajax.trashedCatalogo');
Route::put('ajax/catalogo/restore','AjaxController@restoredCatalogo')->name('ajax.restoreCatalogo');
Route::post('ajax/seguimiento/contacto/{RPD}','AjaxController@seguimientoContacto')->name('ajax.segimientoContacto');

Route::post('ajax/estatusLocalizacion/{RPD?}','AjaxController@estatusLocalizacion')->name('ajax.estatusLocalizacion');

Route::get('/config-cache', function() {
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; 
});

Route::get('/config-clear', function() {
    $exitCode = Artisan::call('config:clear');
    return 'DONE'; 
});

Route::get('/migrate-fresh', function() {
    $exitCode = Artisan::call('migrate:fresh --seed');
    return 'DONE'; 
});

Route::get('/resetCBP', function() {
	//$migrate =Artisan::call('migrate:fresh --seed');
    $clear      =Artisan::call('config:clear');
    $cache      =Artisan::call('config:cache');
    $cacheClear =Artisan::call('cache:clear');
    
    return response()->json([
    	//'migrate' =>$migrate
        'clear'        =>$clear
        ,'cache'       =>$cache
        ,'cache-clear' =>$cacheClear
    ]);
});

src/laravel/app/Models/Sexo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Sexo extends Model{
    use SoftDeletes;

	protected $table      ="sexos";
	protected $primaryKey ='idSexo';
	protected $fillable   =[
		'nombreSexo'
	];
	
	public function getNombreAttribute(){
    	return $this->nombreSexo;
    }

    public function getIdAttribute(){
    	return $this->idSexo;
    }
}

src/laravel/resources/views/layouts/_header.blade.php
<nav class="topnav navbar navbar-expand shadow navbar-light bg-white" id="sidenavAccordion">
    <a class="navbar-brand d-none d-sm-block" href="">
        {{ config('app.name', 'Laravel') }}
        
    </a>
        
    <button class="btn btn-icon btn-transparent-dark order-1 order-lg-0 mr-lg-2" id="sidebarToggle" href="#">
        <i data-feather="menu"></i>
    </button>

    <div class="cbp-center text-center">
            {{ config('app.nameLarge','') }}
            <br>
            {{ config('app.nameShort','') }}
    </div>
    
    
    <!--<form class="form-inline mr-auto d-none d-lg-block">
        <input class="form-control form-control-solid mr-sm-2" type="search" placeholder="Search" aria-label="Search" />
    </form>-->
    
    <ul class="navbar-nav align-items-center ml-auto">
    	@guest
    		<li class="nav-item dropdown no-caret mr-3 ">
                <a  class ="btn "href="{{ route('login') }}">
                	Login
                </a>
            </li>
    	@endguest
        @auth
            <li class="nav-item dropdown no-caret mr-3 dropdown-notifications">
                <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownAlerts" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="bell"></i>
                </a>
            </li>

            <li class="nav-item dropdown no-caret mr-3 dropdown-notifications">
                <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownMessages" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i data-feather="mail"></i>
                </a>
            </li>

            <li class="nav-item dropdown no-caret mr-3 dropdown-user">
                <a class="btn btn-icon btn-transparent-dark dropdown-toggle" id="navbarDropdownUserImage" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i data-feather="user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right border-0 shadow animated--fade-in-up" aria-labelledby="navbarDropdownUserImage">
                    <h6 class="dropdown-header d-flex align-items-center">
                        <i data-feather="user"></i>
                        <div class="dropdown-user-details">
                            <div class="dropdown-user-details-name">
                                {{ auth()->user()->nombreCompleto }}
                            </div>
                            <div class="dropdown-user-details-email">
                                {{ auth()->user()->email}}
                            </div>
                        </div>
                    </h6>
                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" 
                        href=""
                        >
                        <div class="dropdown-item-icon">
                            <i data-feather="settings"></i>
                        </div>
                        Acerca de
                    </a>
                    <form action="{{ route('logout') }}" method="POST" id="frmLogout">
                        @csrf @method('POST')
                        <a class="dropdown-item" href="#" id="lnkLogout">
                            <div class="dropdown-item-icon"><i data-feather="log-out"></i></div>
                            Cerrar sesión
                        </a>
                    </form>
                </div>
            </li>
        @endauth
    </ul>
</nav>

src/laravel/resources/views/layouts/_menu.blade.php
<div class="nav accordion" id="accordionCBP">
    <div class="sidenav-menu-heading">
        Registros CBP
    </div>
    
    <a class="nav-link collapsed" href="javascript:void(0);" 
        data-toggle="collapse" 
        data-target="#cbp" 
        aria-expanded="false" 
        aria-controls="dashboard">

            <div class="nav-link-icon">
                <i data-feather="activity"></i>
            </div>
            CBP
            <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>            
    </a>
        
    <div class="{{ (in_array(Request::route()->getName(),['RPD.registro','RPD.index','RPD.editar','RPD.seguimiento']))?'collapsed':'collapse' }}" id="cbp" data-parent="#accordionCBP">
        <nav class="sidenav-menu-nested nav accordion" id="accordionSidenavPages">
            <div class="nav accordion" id="accordionSidenav">                    
                <a class="nav-link collapsed" href="{{ route('RPD.registro') }}">
                    <div class="nav-link-icon">
                        <i data-feather="user-plus"></i>
                    </div>
                    Nuevo registro
                </a>
                <a class="nav-link collapsed" href="{{ route('RPD.index') }}">
                    <div class="nav-link-icon">
                        <i data-feather="list"></i>
                    </div>
                    Ver registros
                </a>
            </div>
        </nav>
    </div>
</div>



@can('view',auth()->user())
    <div class="nav accordion" id="accordionAdmin">
        <div class="sidenav-menu-heading">
            Administración
        </div>
        
        <a class="nav-link collapsed" href="javascript:void(0);" 
            data-toggle="collapse" 
            data-target="#usuarios" 
            aria-expanded="false" 
            aria-controls="dashboard">

                <div class="nav-link-icon">
                    <i data-feather="activity"></i>
                </div>
                CBP usuarios
                <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>            
        </a>
        
        <div class="{{ (in_array(Request::route()->getName(),['usuario.index','usuario.crear']))?'collapsed':'collapse' }}" id="usuarios" data-parent="#accordionAdmin">
            <nav class="sidenav-menu-nested nav accordion" id="accordionSidenavPages">
                    <div class="nav accordion" id="accordionSidenav">                    
                        <a class="nav-link collapsed" href="{{ route('usuario.index') }}">
                            <div class="nav-link-icon">
                                <i data-feather="square"></i>
                            </div>
                            Ver usuarios
                        </a>
                         <a class="nav-link collapsed" href="{{ route('usuario.crear') }}">
                            <div class="nav-link-icon">
                                <i data-feather="square"></i>
                            </div>
                            Registrar usuario
                        </a>
                    </div>
            </nav>
        </div>
        

        <a class="nav-link collapsed" href="javascript:void(0);" 
            data-toggle="collapse" 
            data-target="#desplegables" 
            aria-expanded="false" 
            aria-controls="dashboard">

                <div class="nav-link-icon">
                    <i data-feather="activity"></i>
                </div>
                CBP Catálogos
                <div class="sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>            
        </a>
        <div class="{{ (in_array(Request::route()->getName(),['catalogo.index']))?'collapsed':'collapse' }}" id="desplegables" data-parent="#accordionAdmin">
            <nav class="sidenav-menu-nested nav accordion" id="accordionSidenavPages">
                    <div class="nav accordion" id="accordionSidenav">                    
                        <a class="nav-link collapsed" href="{{ route('catalogo.index') }}">
                            <div class="nav-link-icon">
                                <i data-feather="square"></i>
                            </div>
                            Ver catálogos
                        </a>
                    </div>
            </nav>
        </div>
            
        
    </div>
@endcan

@include('RPD._informacionGeneralRPD')

src/laravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
        
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{{ config('app.name', 'Laravel') }}</title>

        
        @include('compartidos._links')
        
        @include('compartidos._scripts')
        @yield('scripts')
    </head>
    <body class="nav-fixed">
        
       @include('layouts._header');
        

        <div id="layoutSidenav">

            <div id="layoutSidenav_nav">                
                <nav class="sidenav shadow-right sidenav-dark">
                    
                    <div class="sidenav-menu">
                        @include('layouts._menu')
                    </div>

                    <div class="sidenav-footer">
                        <div class="sidenav-footer-content">
                            @auth
                                <div class="sidenav-footer-subtitle">
                                    Bienvenid@:
                                </div>
                                <div class="sidenav-footer-title">
                                    {{ auth()->user()->nombre }}
                                </div>
                            @endauth
                        </div>
                    </div>
                </nav>


            </div>
            
            <div id="layoutSidenav_content">
                <main>
                    <div class="page-header pb-10 ">
                        <div class="row">
                            <div class="col-lg-12">
                                @include('compartidos._errors')
                                @include('compartidos._message')
                            </div>
                        </div>
                    </div>
                    <div class="container-fluid mt-n10">
                        <div class="row">
                            <div class="col-lg-12">
                                @yield('content')
                            </div>
                        </div>
                    </div>
                </main>
                @include('compartidos._footer')
            </div>

        </div>
        
    </body>
</html>